exports.catch_errors = action => (req, res, next) =>  action(req, res).catch(next)